ALTER TABLE feature_toggle ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE feature_toggle ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE environment ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE api_key ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE api_key ALTER COLUMN expires_at TYPE TIMESTAMPTZ;

ALTER TABLE app_user ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE app_user ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

CREATE INDEX idx_api_key_created_at ON api_key (created_at DESC);
